### ISSUE TITLE
FE-As a user, when I click the app logo,I am navigated back to home page

### ISSUE THREAD

**Issue by KarimAl-Rashdan** [Garden-Grow-Turing/garden-grow-fe#12]
As a user...

- [x] I want to see the logo persist on each page view-main, plant view, My Garden, user profile
- [x] I want to see a hover functionality on logo
- [x] I want to click the logo and be navigated to the main page
- [x] I want an intuitive user experience

Acceptance Criteria:

- Follow the wireframe for the main view of webpage
- Logo should be obvious that it is clickable
- Aim to have this user-friendly

**Comment by cieragrace** [comment]
if there is time add hover effect
